from app.prompts.analyze import ANALYZE_PROMPT_TEMPLATE
from app.prompts.image import IMAGE_DESCRIBE_PROMPT
from app.prompts.til import TIL_GENERATE_PROMPT, TIL_SINGLE_PROMPT

__all__ = ["ANALYZE_PROMPT_TEMPLATE", "IMAGE_DESCRIBE_PROMPT", "TIL_GENERATE_PROMPT", "TIL_SINGLE_PROMPT"]
